### ISSUE TITLE
Can't run the project with `npm run dev`

### ISSUE THREAD

**Issue by hoppingninja666** [Copay/cPlayer#44]
I get the following error
`ERROR in ./src/example.ts
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /home/user/Documents/coding/cPlayer/node_modules/@babel/helper-compilation-targets/package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:290:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:513:3)
    at resolveExports (internal/modules/cjs/loader.js:432:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:472:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)`

I am using nodejs version 14.16.1

**Comment by hoppingninja666** [comment]
I solved it by removing all reference of babel from the webpack config files.
